# Generated by Django 3.2 on 2021-07-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='project_name',
        ),
        migrations.AddField(
            model_name='project',
            name='layers',
            field=models.JSONField(default={}),
        ),
    ]
