# Generated by Django 3.2 on 2021-07-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20210729_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='layers',
            field=models.JSONField(default=dict),
        ),
    ]
